### ISSUE TITLE
Updates on the release of the dataset?

### ISSUE THREAD

**Issue by Barbany** [navervision/CompoDiff#3]
Will the dataset be made available?

**Comment by geonm** [comment]
Sure thing!

Please stay tuned!

**Comment by hanwen0529** [comment]
When will the dataset be released? Thanks!

**Comment by SanghyukChun** [comment]
We expect to release the dataset in late Nov. The dataset is 4.1TB and will be served as the [webdataset](https://github.com/webdataset/webdataset) format.

**Comment by SanghyukChun** [comment]
Closed via #5
