### ISSUE TITLE
When will the dataset be released? Thanks!

### ISSUE THREAD

**Issue by Pefect96** [navervision/CompoDiff#5]

**Comment by geonm** [comment]
It will be this week or last week!

Thank you for waiting.

The dataset is in tar-compressed webdataset format and should be very easily accessible using the huggingface datasets library.

**Comment by davidpicard** [comment]
Hello!

Any news with respect to the release of your dataset? It'd be really helpful to have it as soon as possible.
Thanks!

++
David.

**Comment by geonm** [comment]
Data is still being uploaded. However, because the data capacity is very
large (terabytes), it takes longer than expected and will end soon.

2023년 12월 14일 (목) 00:14, David Picard ***@***.***>님이 작성:

**Comment by geonm** [comment]
@Pefect96 @davidpicard

Thank you for your patience!

SynthTriplets18M is now hosted at https://huggingface.co/datasets/navervision/SynthTriplets18M

We plan to document how to use SynthTriplets18M in the README either today or tomorrow.

Feel free to either wait or check it out right away.

**Comment by davidpicard** [comment]
Thank you!
